# Generated by Django 5.0.3 on 2024-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0002_rename_f_name_employee_fathername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank='true', null='true'),
            preserve_default='true',
        ),
    ]
