# Generated by Django 5.0.3 on 2024-04-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='empattendence',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteapp.department'),
        ),
    ]
